
params:
  seed: 42

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 5.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [256, 128, 64]
      activation: relu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: cart_double_pendulum_direct_sac
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 0.1
    max_epochs: 5000
    num_steps_per_episode: 8
    save_best_after: 500
    save_frequency: 1000
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 5e-3
    actor_lr: 5e-4
    critic_lr: 5e-4
    critic_tau: 5e-3
    batch_size: 16384
    learnable_temperature: True
    num_warmup_steps: 10 # total number of warmup steps: num_actors * num_steps_per_episode * num_warmup_steps
    replay_buffer_size: 1000000
    num_actors: -1
    grad_norm: 1.0

